### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by JacquesLG** [inmcm/micropyGPS#5]
Hello,
I'm getting this error whilst trying to parse a string:

```
Traceback (most recent call last):
  File "gps.py", line 30, in <module>
    my_gps.update(x)
  File "/home/pi/MNT-GPS/micropyGPS.py", line 573, in update
    ascii_char = ord(new_char)
TypeError: ord() expected string of length 1, but int found
```

Here is my full code:
```

import serial
import time
import os
from micropyGPS import MicropyGPS
import pifacecad

my_gps = MicropyGPS()

cad = pifacecad.PiFaceCAD()
cad.lcd.backlight_on()
cad.lcd.blink_off() 

# Set up serial:
ser = serial.Serial(
    port='/dev/ttyUSB0',\
    baudrate=4800,\
    parity=serial.PARITY_NONE,\
    stopbits=serial.STOPBITS_ONE,\
    bytesize=serial.EIGHTBITS,\
        timeout=1)


# Main program loop:
while True:
    
    my_sentence = ser.readline()
    for x in my_sentence:
            my_gps.update(x)
    lat = my_gps.latitude
    lon = my_gps.longitude
    cad.lcd.clear()
    cad.lcd.write("%s\n%s" % (lat, lon)) 
    print("%s\n%s" % (lat, lon)) 
    time.sleep(2)

```

Thanks for the help :)

**Comment by inmcm** [comment]
```ser.readline()``` returns a bytes object made up of ints and ```update()``` expects a single string character. The simplest solution is change you serial reader to:
```python
y_sentence = ser.readline().decode()
``` 
then the for loop will feed characters instead of integers to the update function

**Comment by JacquesLG** [comment]
Thank you very much
Have good day
